Upgrade golangci-lint
mattermost/circleci-orbs pull request #20
Opened 2020-10-01 15:48 UTC by cpoile

#### Summary
- 1.24.0 was failing while checking the incident response plugin, we had to stop using it: https://github.com/mattermost/mattermost-plugin-incident-response/pull/309
- 1.31.0 works

2020-10-01 22:47 UTC, hanzei requested changes
A lot of our plugins are using the latest version of the plugin orb for every build like e.g. Agenda https://github.com/mattermost/mattermost-plugin-agenda/blob/0feab819b7e8272bc5273c1ca2135e044bd85600/.circleci/config.yml#L4

With bumping the version of golangci-lint we risk breaking CI for multiple of our plugins. Would you suggest fixing this issues post merge?

2020-10-02 13:15 UTC, cpoile commented
@hanzei We can use a parameter for the job. I'm pretty sure this will work, but I'm not sure how to test this without pushing. I can't find a solution online for using an orb from a PR's hash, do you know?

2020-10-02 13:16 UTC, cpoile commented on plugin-ci/orb.yml
> +        default: 1.24.0
removing the default from above (making it a required parameter) and putting the default here -- this keeps the default value in one place for future changes.

2020-10-07 23:28 UTC, lieut-data commented
I'd be inclined to fix these issues post merge -- if the plugins aren't broken on 1.24.0 now, they'll probably start failing that way anyway. If we can't update the version centrally here, I'd argue we shouldn't be sharing the orbs in the first place since we'll be restricted by the lowest common denominator. Presumably plugins that choose not to fix can just pin their orb as required?

2020-10-08 20:43 UTC, hanzei commented
I'd be inclined to fix these issues post merge -- if the plugins aren't broken on 1.24.0 now, they'll probably start failing that way anyway. If we can't update the version centrally here, I'd argue we shouldn't be sharing the orbs in the first place since we'll be restricted by the lowest common denominator. Presumably plugins that choose not to fix can just pin their orb as required?



@lieut-data I agree that we are bound to the lowest common denominator. But for historical reasons, all plugins use the latest version, which might not be a good idea.

The pain point is that we will have to touch multiple plugins after the version bump. We can bump the version when we ensure every CI pipeline gets fixed soon after the bump

2020-10-08 20:48 UTC, lieut-data commented
Thanks for the extra context, @hanzei. Right now, we've had to disable golangci-lint manually for incident response, but I'd love to get that restored. I'm not a huge fan of parameterizing this property instead of using the existing "orb version" parameter, since it feels like a workaround. If we're committed to this approach, it might be easier for us to just "fork" the orb for our own purposes.

Thoughts on next steps? My gut says to either merge this and deal with the fallout (possibly by just pinning), or just abandon this PR altogether.

2020-10-08 20:51 UTC, hanzei commented
I'm fine with merging and dealing with the consequences :+1:

2020-10-08 20:51 UTC, hanzei commented
@cpoile Would you mind reverting back to https://github.com/mattermost/circleci-orbs/pull/20/commits/bdff182d9ac67ddd75236ab44580867cb0a06bdb?

2020-10-08 20:54 UTC, lieut-data approved these changes

2020-10-08 20:54 UTC, hanzei approved these changes

2020-10-08 20:55 UTC, lieut-data commented
@hanzei, is QA review required here? Or do we just treat this as developer/build related?

2020-10-08 20:55 UTC, hanzei commented
Getting QA review for these kind of PRs is just not worth it

2020-10-08 20:57 UTC, hanzei commented
I've submitted three PRs to fix the linter issues:
- https://github.com/mattermost/mattermost-plugin-agenda/pull/67
- https://github.com/mattermost/mattermost-plugin-demo/pull/122
- https://github.com/mattermost/mattermost-plugin-solar-lottery/pull/41

Please take a look at them so we can merge them and this PR soon

2020-10-08 20:59 UTC, lieut-data commented
You're the best, @hanzei! I've approved those PRs -- very light touches, which is good!

2020-10-13 08:06 UTC, hanzei commented
@cpoile Is this PR ready to get merged?

2020-10-13 14:58 UTC, merged